txt_data = "I like pizza."

file_path = "file_writing.txt"

with open(file=file_path, mode="w") as file: #w is for writing (You can also use \n or ' ' chars)...
    #x will write on files that don't exist (so will w)...
    # a is for appending to a file but use a '\n' char...
    # and r is for reading...
    file.write(txt_data)
    print(f"succesfully write '{file_path}' was created.")
